number = @{ sign? ~ int }
  sign = { "+" | "-" }
  int = @{ ASCII_DIGIT+ }

op = _{ plus | minus | times | slash }
  plus = { "+" }
  minus = { "-" }
  times = { "*" }
  slash = { "/" }

custom_die = { "[" ~ int ~ ("," ~ int )* ~ "]" }
roll = { number ~ ^"d" ~ (custom_die | int) }

expr = { term ~ (op ~ term)* }
term = _{ roll | number | "(" ~ expr ~ ")" }

calc = _{ SOI ~ expr ~ EOI }

WHITESPACE = _{ " " | "\t" | "\n" }
COMMENT = _{ "/*" ~ (!"*/" ~ ANY)* ~ "*/" }
